trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GITHUB_USERNAME: 'ahmetyanik'
  GITHUB_TOKEN: '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'

steps:
# Node.js Versiyonunu Ayarla
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Set up Node.js'

# Uygulama Bağımlılıklarını Yükle ve Derle
- script: |
    npm config set openssl-legacy-provider true
    npm install
    npm run build
  displayName: 'Install dependencies and build React app'

# GitHub Prod Repo'ya Push Et
- script: |
    git config --global user.name 'Ahmet Yanik'
    git config --global user.email 'ahmet.yanik@nteam.com'

    # Git Remote'yi temizle ve bağlantıyı doğrudan git push ile yap
    git remote remove prod_repo
    git push https://$(GITHUB_USERNAME):$(GITHUB_TOKEN)@github.com/ahmetyanik/WheatherPROD.git HEAD:main
  displayName: 'Push changes to GitHub Prod Repo'
