# azure-pipelines.yml

trigger:
- main

resources: 
  repositories:
    - repository: self
      type: github
      name: ahmetyanik/Weather
      endpoint: tokenliAhmet

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Pipeline çalışıyor!"
  displayName: 'Test Script'
