trigger:
  branches:
    include:
      - main  # Test reposundaki main branch tetiklenecek

pool:
  vmImage: 'ubuntu-latest'

steps:
  # 1. Test Repodan Kod Çek
  - task: Checkout@1
    inputs:
      clean: true

  # 2. Prod Repoya Push Et
  - script: |
      git config --global user.name "Azure DevOps"
      git config --global user.email "devops@example.com"

      # Prod reponun URL'si ve branch'i
      git remote add prod_repo https://<PROD_REPO_URL>.git
      git fetch prod_repo
      git push prod_repo main:main
    displayName: "Push changes to Prod Repo"
